services:
  pureride-client:
    container_name: pureride-client
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/pureride-client
    working_dir: /usr/src/pureride-client

    networks:
      client-network:

    # PRODUCTION
    command: bash -c " yarn  && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
