export enum NoticeCategory {
	FAQ = 'FAQ',
	TERMS = 'TERMS',
	INQUIRY = 'INQUIRY',
}

export enum NoticeStatus {
	HOLD = 'HOLD',
	ACTIVE = 'ACTIVE',
	DELETE = 'DELETE',
}
export enum NoticeType {
	PROMOTION = 'PROMOTION',
	NEW_ARRIVAL = 'NEW ARRIVAL ',
	MAINTENANCE = 'MAINTENANCE',
	SAFETY = 'SAFETY',
	WEBSITE_UPDATE = 'WEBSITE UPDATE',
	LEGAL_POLICY = 'LEGAL POLICY',
	GENERAL_ANNOUNCEMENT = 'GENERAL ANNOUNCEMENT',
}
