export enum ProductType {
	SPORTBIKE = 'SPORTBIKE',
	SKUTER = 'SKUTER',
	QUADRICYCLE = 'QUADRICYCLE',
}

export enum ProductStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum ProductLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
}

export enum ProductEngineSize {
	BASE = "BASE",
	LIGHTWEIGHT = 'LIGHTWEIGHT',
	ENTRYLEVEL = 'ENTRYLEVEL',
	INTERMEDIATE = 'INTERMEDIATE',
	ADVANCED="ADVANCED",
	HEAVY = 'HEAVY',
}

export enum ProductFuelType {
	GASOLINE = 'GASOLINE',
	ELECTRICITY = 'ELECTRICITY',
}
